export interface MenuItemSize {
  label: string;
  shortLabel: string;
  price: number;
}

export interface MenuItem {
  id: string;
  name: string;
  description: string;
  category:
    | 'pizza-veg'
    | 'pizza-nonveg'
    | 'pizza-special'
    | 'burger-sandwich'
    | 'momo'
    | 'cfc-nonveg-sides'
    | 'sides-pasta'
    | 'noodles-rice-rolls'
    | 'drinks-desserts'
    | 'combos';
  highlightGroup?: 'pizza' | 'burger' | 'momo' | 'cfc' | 'all';
  dietary: 'veg' | 'non-veg';
  price: number;
  sizes?: MenuItemSize[];
  tag?: string;
  popular?: boolean;
  image: string;
  inStock?: boolean;
}

export interface MenuHighlight {
  id: 'pizza' | 'burger' | 'momo' | 'cfc';
  title: string;
  subtitle: string;
  description: string;
  startingPrice: number;
  itemCount: string;
  signatureDishes: string[];
  image: string;
  targetCategory: string;
}

export const ASSETS = {
  realLogo: '/src/assets/images/hashtag_real_brand_logo.png',
  heroPizza: '/src/assets/images/hero_supreme_pizza_1790938618890.jpg',
  categoryPizza: '/src/assets/images/category_artisan_pizza_1790938632403.jpg',
  categoryBurger: '/src/assets/images/category_gourmet_burger_1790938646377.jpg',
  categoryMomo: '/src/assets/images/category_nepali_momo_1790938658362.jpg',
  categoryCfc: '/src/assets/images/category_crispy_chicken_1790938670645.jpg',
  founderKitchen: '/Hashtag Pizza_ A Vibrant Restaurant Collage.png',
  interiorCollage: '/Hashtag Pizza_ A Vibrant Restaurant Collage.png',
  conveyorOven: '/src/assets/images/conveyor_belt_oven_1790958702165.jpg',
  diningSitting: '/src/assets/images/hashtag_dining_sitting_1790958715120.jpg',
  storefrontExterior: '/src/assets/images/hashtag_storefront_rb_1790958726183.jpg',
};

export const BRAND_COPY = {
  mainTagline: 'Think Food, Think Hashtag Pizza.',
  secondaryTagline: 'Delivering Happiness in Birgunj since 2022.',
  heroHook: 'World-class quality pizza and burgers, finally home in Birgunj.',
  menuCallout:
    "From our signature crispy chicken (CFC) to our perfectly loaded Supreme Pizzas—we don't just make food, we make memories.",
  founderTitle: 'From Amazon & Daraz to the Heart of Birgunj',
  founderStoryPrimary:
    'After years in the corporate world at Amazon and Daraz, our founder Bhasker returned home with one mission: to bring the authentic quality of international pizzas and burgers to his community. Every slice at Hashtag Pizza is a piece of that journey.',
  founderStorySecondary:
    'Launched in 2022 at RB Complex, Adarshnagar, Hashtag Pizza introduced Birgunj to store-made fresh daily dough, 100% real pulled mozzarella, and an automated commercial 24-inch Conveyor Belt Oven for mathematically even baking every time.',
  ovenTitle: '24-Inch Commercial Conveyor Belt Oven',
  ovenSubtitle: 'Automated Consistency · Zero Burnt Edges · Perfect Melt',
  ovenDescription:
    'Hashtag Pizza does not use unpredictable wood or stone ovens. Instead, we bake exclusively with a commercial 24-inch conveyor belt oven. Precise multi-zone heating and calibrated speed ensure every pizza emerges with a crisp golden base, tender crumb, and bubbly melted cheese.',
  sittingAreaTitle: 'Cozy Customer Sitting & Dining Area',
  sittingAreaSubtitle: 'Air-Conditioned Comfort · Booth Seating · Warm Vibe',
  sittingAreaDescription:
    'Step into our welcoming dine-in restaurant at RB Complex with light-wood tables, comfortable cushioned booth seats, industrial dining chairs, and warm ambient LED lighting—ideal for family dinners, friends gatherings, and student hangouts.',
  kitchenSetupTitle: 'Modern Commercial Kitchen Setup',
  kitchenSetupSubtitle: 'Hygienic Prep Stations · Digital Order Display · Daily Fresh Dough',
  kitchenSetupDescription:
    'Our kitchen features separate prep and assembly counters, dedicated fryers for CFC and Kurkure Momos, and a direct service counter with a live "Your Order Is Ready" digital queue screen for fast, transparent service.',
};

export const CONTACT_INFO = {
  address: 'RB Complex, Loharpatti, Adarshnagar, Birgunj',
  fullAddress: 'Shop No. 01, Ground Floor, RB Complex, Loharpatti, Adarshnagar, Birgunj',
  primaryPhone: '9861370721',
  landline: '051-591718',
  orderPhonesDisplay: '9861370721 / 051-591718',
  mobileNumbers: ['9861370721', '9828203930', '9764240072'],
  whatsapp: '9779861370721',
  whatsappDisplay: '9861370721',
  email: 'hashtagpizzainfo@gmail.com',
  instagram: 'https://instagram.com/hashtagpizza.np',
  instagramHandle: '@hashtagpizza.np',
  facebook: 'https://www.facebook.com/HashtagPizzaa/',
  hours: '11:30 AM – 9:30 PM Daily',
  takeAppUrl: 'https://take.app/hashtagpizza',
  services: ['Dine In', 'Take Away', 'Delivery'],
};

export const MENU_HIGHLIGHTS: MenuHighlight[] = [
  {
    id: 'pizza',
    title: 'Artisan Pizzas',
    subtitle: 'Classic, Deluxe, Premium & Supreme',
    description:
      'Hand-stretched daily dough baked with 100% real mozzarella and cheddar. Available in Pizza Lovers personal size, Small, Medium, and Large.',
    startingPrice: 180,
    itemCount: '45+ Pizzas · S / M / L Sizes',
    signatureDishes: [
      'Hashtag Special Chicken Pizza',
      'Paneer Overloaded',
      'Peppy Paneer',
      'Margherita',
    ],
    image: ASSETS.categoryPizza,
    targetCategory: 'pizza-veg',
  },
  {
    id: 'burger',
    title: 'Burgers & Sandwiches',
    subtitle: 'In-Store Patties & Zinger Crunch',
    description:
      'Stacked with crispy Aloo Tikki, Crunchy Paneer, in-store fried Chicken Patties, or Zinger fillets with melted cheese and signature sauces.',
    startingPrice: 100,
    itemCount: '19 Varieties · Veg & Chicken',
    signatureDishes: [
      'Maharaja Burger',
      'Chicken Zinger Cheese Burger',
      'Crispy Paneer Cheese Burger',
      'Crispy Aloo Tikki Burger',
    ],
    image: ASSETS.categoryBurger,
    targetCategory: 'burger-sandwich',
  },
  {
    id: 'momo',
    title: 'Signature Momos',
    subtitle: 'Veg, Paneer & Chicken (9 Styles Each)',
    description:
      'Freshly pleated daily and served Steamed, Fried, Pan-Fried, Crispy, Kurkure, Chilly, Jhol, Manchurian, or rich creamy Malai style.',
    startingPrice: 180,
    itemCount: '27 Varieties · 9 Styles',
    signatureDishes: [
      'Chicken Kurkure Momo',
      'Chicken Jhol Momo',
      'Paneer Malai Momo',
      'Veg Chilly Momo',
    ],
    image: ASSETS.categoryMomo,
    targetCategory: 'momo',
  },
  {
    id: 'cfc',
    title: 'CFC & Crispy Chicken',
    subtitle: 'Boneless Strips, Popcorn & Non-Veg Sides',
    description:
      'Crunchy golden Boneless Chicken Strips (4 to 12 pcs), Crispy Chicken Popcorn, Chicken Nuggets, Fried Sausages, and Chilly Chicken.',
    startingPrice: 180,
    itemCount: '14 Varieties · Freshly Fried',
    signatureDishes: [
      'Boneless Chicken Strips (4–12 Pcs)',
      'Crispy Chicken Popcorn',
      'Chicken Nuggets',
      'Stuffed Chicken Garlic Bread',
    ],
    image: ASSETS.categoryCfc,
    targetCategory: 'cfc-nonveg-sides',
  },
];

export const MENU_CATEGORIES = [
  { id: 'all', name: 'All Menu' },
  { id: 'pizza-veg', name: 'Veg Pizza (S/M/L)' },
  { id: 'pizza-nonveg', name: 'Non-Veg Pizza (S/M/L)' },
  { id: 'pizza-special', name: 'Pizza Lovers & Momo Pizza' },
  { id: 'momo', name: 'Momos (Veg / Paneer / Chicken)' },
  { id: 'burger-sandwich', name: 'Burgers & Sandwiches' },
  { id: 'cfc-nonveg-sides', name: 'CFC Strips & Non-Veg Sides' },
  { id: 'sides-pasta', name: 'Garlic Bread, Fries, Pasta & Appetizers' },
  { id: 'noodles-rice-rolls', name: 'Noodles, Rice, Rolls & Bowls' },
  { id: 'drinks-desserts', name: 'Shakes, Mocktails & Desserts' },
  { id: 'combos', name: 'Combo Offers' },
];

export const MENU_ITEMS: MenuItem[] = [
  // ==========================================
  // 1. VEG CLASSIC PIZZA (S / M / L)
  // ==========================================
  {
    id: 'vc-1',
    name: 'Margherita Pizza',
    description: 'Classic pizza topped with 100% real pulled Mozzarella cheese. (Extras: Extra Cheese +Rs.80, Cheese Burst +Rs.120)',
    category: 'pizza-veg',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 220,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 220 },
      { label: 'Medium (M)', shortLabel: 'M', price: 440 },
      { label: 'Large (L)', shortLabel: 'L', price: 650 },
    ],
    tag: 'Veg Classic',
    popular: true,
    image: ASSETS.categoryPizza,
  },
  {
    id: 'vc-2',
    name: 'Cheezy Onion Pizza',
    description: 'Mozzarella and Cheddar cheese blend topped with crunchy fresh onions.',
    category: 'pizza-veg',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 260,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 260 },
      { label: 'Medium (M)', shortLabel: 'M', price: 480 },
      { label: 'Large (L)', shortLabel: 'L', price: 700 },
    ],
    tag: 'Veg Classic',
    image: ASSETS.categoryPizza,
  },
  {
    id: 'vc-3',
    name: 'Cheezy Tomato Pizza',
    description: 'Mozzarella and Cheddar cheese topped with juicy fresh tomatoes.',
    category: 'pizza-veg',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 260,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 260 },
      { label: 'Medium (M)', shortLabel: 'M', price: 480 },
      { label: 'Large (L)', shortLabel: 'L', price: 700 },
    ],
    tag: 'Veg Classic',
    image: ASSETS.categoryPizza,
  },
  {
    id: 'vc-4',
    name: 'Cheezy Corn Pizza',
    description: 'Mozzarella and Cheddar cheese loaded with sweet golden corn.',
    category: 'pizza-veg',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 260,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 260 },
      { label: 'Medium (M)', shortLabel: 'M', price: 480 },
      { label: 'Large (L)', shortLabel: 'L', price: 700 },
    ],
    tag: 'Veg Classic',
    image: ASSETS.categoryPizza,
  },
  {
    id: 'vc-5',
    name: 'Cheezy Capsicum Pizza',
    description: 'Mozzarella and Cheddar cheese with crisp green capsicum.',
    category: 'pizza-veg',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 260,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 260 },
      { label: 'Medium (M)', shortLabel: 'M', price: 480 },
      { label: 'Large (L)', shortLabel: 'L', price: 700 },
    ],
    tag: 'Veg Classic',
    image: ASSETS.categoryPizza,
  },
  {
    id: 'vc-6',
    name: 'Fresh Veggie Pizza',
    description: 'Mozzarella and Cheddar cheese with fresh onion, capsicum, and tomato.',
    category: 'pizza-veg',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 300,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 300 },
      { label: 'Medium (M)', shortLabel: 'M', price: 550 },
      { label: 'Large (L)', shortLabel: 'L', price: 750 },
    ],
    tag: 'Veg Classic',
    image: ASSETS.categoryPizza,
  },
  {
    id: 'vc-7',
    name: 'Double Cheese Pizza',
    description: 'Loaded with sliced Cheddar cheese, extra Mozzarella cheese, and black olives.',
    category: 'pizza-veg',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 330,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 330 },
      { label: 'Medium (M)', shortLabel: 'M', price: 560 },
      { label: 'Large (L)', shortLabel: 'L', price: 800 },
    ],
    tag: 'Veg Classic',
    popular: true,
    image: ASSETS.categoryPizza,
  },

  // ==========================================
  // 2. VEG DELUXE PIZZA (S / M / L)
  // ==========================================
  {
    id: 'vd-1',
    name: 'Paneer & Onion Pizza',
    description: 'Spiced paneer cubes and crunchy onion loaded with Mozzarella cheese.',
    category: 'pizza-veg',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 330,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 330 },
      { label: 'Medium (M)', shortLabel: 'M', price: 560 },
      { label: 'Large (L)', shortLabel: 'L', price: 800 },
    ],
    tag: 'Veg Deluxe',
    popular: true,
    image: ASSETS.categoryPizza,
  },
  {
    id: 'vd-2',
    name: 'Paneer & Corn Pizza',
    description: 'Soft paneer chunks and sweet golden corn loaded with Mozzarella cheese.',
    category: 'pizza-veg',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 330,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 330 },
      { label: 'Medium (M)', shortLabel: 'M', price: 560 },
      { label: 'Large (L)', shortLabel: 'L', price: 800 },
    ],
    tag: 'Veg Deluxe',
    image: ASSETS.categoryPizza,
  },
  {
    id: 'vd-3',
    name: 'Farm House Pizza',
    description: 'Mozzarella cheese, crunchy onion, capsicum, juicy tomato, and fresh button mushroom.',
    category: 'pizza-veg',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 360,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 360 },
      { label: 'Medium (M)', shortLabel: 'M', price: 600 },
      { label: 'Large (L)', shortLabel: 'L', price: 900 },
    ],
    tag: 'Veg Deluxe',
    popular: true,
    image: ASSETS.heroPizza,
  },
  {
    id: 'vd-4',
    name: 'Corn House Pizza',
    description: 'Mozzarella cheese, onion, capsicum, fresh tomato, and golden sweet corn.',
    category: 'pizza-veg',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 360,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 360 },
      { label: 'Medium (M)', shortLabel: 'M', price: 600 },
      { label: 'Large (L)', shortLabel: 'L', price: 900 },
    ],
    tag: 'Veg Deluxe',
    image: ASSETS.categoryPizza,
  },
  {
    id: 'vd-5',
    name: 'Spicy Mexican Pizza',
    description: 'Cheese, onion, capsicum, tomato, fiery red paprika, and tangy jalapeno.',
    category: 'pizza-veg',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 360,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 360 },
      { label: 'Medium (M)', shortLabel: 'M', price: 600 },
      { label: 'Large (L)', shortLabel: 'L', price: 900 },
    ],
    tag: 'Veg Deluxe',
    image: ASSETS.heroPizza,
  },
  {
    id: 'vd-6',
    name: 'Cheese Dominator Pizza',
    description: 'Sliced Cheddar cheese and pulled Mozzarella cheese topped with black olives.',
    category: 'pizza-veg',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 360,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 360 },
      { label: 'Medium (M)', shortLabel: 'M', price: 600 },
      { label: 'Large (L)', shortLabel: 'L', price: 900 },
    ],
    tag: 'Veg Deluxe',
    image: ASSETS.categoryPizza,
  },
  {
    id: 'vd-7',
    name: 'Veg Pasta Pizza',
    description: 'Mozzarella and Cheddar cheese, onion, capsicum, tomato, and creamy pasta topping.',
    category: 'pizza-veg',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 360,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 360 },
      { label: 'Medium (M)', shortLabel: 'M', price: 600 },
      { label: 'Large (L)', shortLabel: 'L', price: 900 },
    ],
    tag: 'Veg Deluxe',
    image: ASSETS.categoryPizza,
  },

  // ==========================================
  // 3. VEG PREMIUM PIZZA (S / M / L)
  // ==========================================
  {
    id: 'vp-1',
    name: 'Peppy Paneer Pizza',
    description: 'Chunky paneer, crunchy onion, crisp capsicum, and spicy red paprika.',
    category: 'pizza-veg',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 380,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 380 },
      { label: 'Medium (M)', shortLabel: 'M', price: 700 },
      { label: 'Large (L)', shortLabel: 'L', price: 1000 },
    ],
    tag: 'Veg Premium',
    popular: true,
    image: ASSETS.heroPizza,
  },
  {
    id: 'vp-2',
    name: 'Peri Peri Paneer Pizza',
    description: 'Zesty peri-peri spiced paneer, onion, capsicum, and red paprika.',
    category: 'pizza-veg',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 380,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 380 },
      { label: 'Medium (M)', shortLabel: 'M', price: 700 },
      { label: 'Large (L)', shortLabel: 'L', price: 1000 },
    ],
    tag: 'Veg Premium',
    image: ASSETS.heroPizza,
  },
  {
    id: 'vp-3',
    name: 'Paneer Pataka Pizza',
    description: 'Spiced paneer, onion, capsicum, red paprika, and smoky Harissa sauce drizzle.',
    category: 'pizza-veg',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 400,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 400 },
      { label: 'Medium (M)', shortLabel: 'M', price: 750 },
      { label: 'Large (L)', shortLabel: 'L', price: 1050 },
    ],
    tag: 'Veg Premium',
    image: ASSETS.heroPizza,
  },
  {
    id: 'vp-4',
    name: 'Indi Tandoori Paneer Pizza',
    description: 'Tandoori paneer cubes, onion, capsicum, red paprika, and refreshing mint mayo sauce.',
    category: 'pizza-veg',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 400,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 400 },
      { label: 'Medium (M)', shortLabel: 'M', price: 750 },
      { label: 'Large (L)', shortLabel: 'L', price: 1050 },
    ],
    tag: 'Veg Premium',
    popular: true,
    image: ASSETS.heroPizza,
  },
  {
    id: 'vp-5',
    name: 'Deluxe Veggie Pizza',
    description: 'Generous topping of onion, capsicum, mushroom, paneer, golden corn, and extra cheese.',
    category: 'pizza-veg',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 440,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 440 },
      { label: 'Medium (M)', shortLabel: 'M', price: 800 },
      { label: 'Large (L)', shortLabel: 'L', price: 1100 },
    ],
    tag: 'Veg Premium',
    image: ASSETS.heroPizza,
  },

  // ==========================================
  // 4. VEG SUPREME PIZZA (S / M / L)
  // ==========================================
  {
    id: 'vs-1',
    name: 'Veggie Supreme Pizza',
    description: 'Loaded with black olives, onion, capsicum, mushroom, red paprika, sweet corn, and extra cheese.',
    category: 'pizza-veg',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 500,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 500 },
      { label: 'Medium (M)', shortLabel: 'M', price: 900 },
      { label: 'Large (L)', shortLabel: 'L', price: 1200 },
    ],
    tag: 'Veg Supreme',
    popular: true,
    image: ASSETS.heroPizza,
  },
  {
    id: 'vs-2',
    name: 'Paneer Overloaded Pizza',
    description: 'Ultimate double paneer feast with capsicum, red paprika, black olives, jalapenos, and extra cheese.',
    category: 'pizza-veg',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 550,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 550 },
      { label: 'Medium (M)', shortLabel: 'M', price: 950 },
      { label: 'Large (L)', shortLabel: 'L', price: 1300 },
    ],
    tag: 'Veg Supreme',
    popular: true,
    image: ASSETS.heroPizza,
  },
  {
    id: 'vs-3',
    name: 'Veggie Paradise Pizza',
    description: 'Golden corn, black olives, crisp capsicum, fiery red paprika, mushroom, and molten cheese.',
    category: 'pizza-veg',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 550,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 550 },
      { label: 'Medium (M)', shortLabel: 'M', price: 950 },
      { label: 'Large (L)', shortLabel: 'L', price: 1300 },
    ],
    tag: 'Veg Supreme',
    image: ASSETS.heroPizza,
  },

  // ==========================================
  // 5. CLASSIC NON-VEG PIZZA (S / M / L)
  // ==========================================
  {
    id: 'nvc-1',
    name: 'Cheezy Chicken Sausage Pizza',
    description: 'Savory smoked chicken sausage rounds over melted Mozzarella and Cheddar cheese.',
    category: 'pizza-nonveg',
    highlightGroup: 'pizza',
    dietary: 'non-veg',
    price: 280,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 280 },
      { label: 'Medium (M)', shortLabel: 'M', price: 550 },
      { label: 'Large (L)', shortLabel: 'L', price: 800 },
    ],
    tag: 'Non-Veg Classic',
    image: ASSETS.heroPizza,
  },
  {
    id: 'nvc-2',
    name: 'Chicken Golden Delight Pizza',
    description: 'Herb-grilled chicken chunks, sweet golden corn, and extra pulled Mozzarella cheese.',
    category: 'pizza-nonveg',
    highlightGroup: 'pizza',
    dietary: 'non-veg',
    price: 320,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 320 },
      { label: 'Medium (M)', shortLabel: 'M', price: 620 },
      { label: 'Large (L)', shortLabel: 'L', price: 880 },
    ],
    tag: 'Non-Veg Classic',
    popular: true,
    image: ASSETS.heroPizza,
  },
  {
    id: 'nvc-3',
    name: 'BBQ Chicken & Onion Pizza',
    description: 'Smoky barbecue glazed chicken with crunchy red onions and Mozzarella cheese.',
    category: 'pizza-nonveg',
    highlightGroup: 'pizza',
    dietary: 'non-veg',
    price: 320,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 320 },
      { label: 'Medium (M)', shortLabel: 'M', price: 620 },
      { label: 'Large (L)', shortLabel: 'L', price: 880 },
    ],
    tag: 'Non-Veg Classic',
    image: ASSETS.heroPizza,
  },

  // ==========================================
  // 6. DELUXE NON-VEG PIZZA (S / M / L)
  // ==========================================
  {
    id: 'nvd-1',
    name: 'Chicken Fiesta Pizza',
    description: 'Grilled chicken, crunchy onion, green capsicum, and spicy red paprika.',
    category: 'pizza-nonveg',
    highlightGroup: 'pizza',
    dietary: 'non-veg',
    price: 400,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 400 },
      { label: 'Medium (M)', shortLabel: 'M', price: 720 },
      { label: 'Large (L)', shortLabel: 'L', price: 1050 },
    ],
    tag: 'Non-Veg Deluxe',
    popular: true,
    image: ASSETS.heroPizza,
  },
  {
    id: 'nvd-2',
    name: 'Peri Peri Chicken Pizza',
    description: 'Zesty peri-peri spiced chicken chunks, onion, capsicum, and red paprika.',
    category: 'pizza-nonveg',
    highlightGroup: 'pizza',
    dietary: 'non-veg',
    price: 440,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 440 },
      { label: 'Medium (M)', shortLabel: 'M', price: 800 },
      { label: 'Large (L)', shortLabel: 'L', price: 1100 },
    ],
    tag: 'Non-Veg Deluxe',
    image: ASSETS.heroPizza,
  },
  {
    id: 'nvd-3',
    name: 'Chicken Mushroom Pizza',
    description: 'Tender roasted chicken chunks paired with fresh button mushrooms and Mozzarella.',
    category: 'pizza-nonveg',
    highlightGroup: 'pizza',
    dietary: 'non-veg',
    price: 440,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 440 },
      { label: 'Medium (M)', shortLabel: 'M', price: 800 },
      { label: 'Large (L)', shortLabel: 'L', price: 1100 },
    ],
    tag: 'Non-Veg Deluxe',
    image: ASSETS.heroPizza,
  },
  {
    id: 'nvd-4',
    name: 'Chicken Pasta Pizza',
    description: 'Mozzarella and Cheddar cheese, spiced chicken, onion, capsicum, and creamy pasta topping.',
    category: 'pizza-nonveg',
    highlightGroup: 'pizza',
    dietary: 'non-veg',
    price: 480,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 480 },
      { label: 'Medium (M)', shortLabel: 'M', price: 880 },
      { label: 'Large (L)', shortLabel: 'L', price: 1200 },
    ],
    tag: 'Non-Veg Deluxe',
    image: ASSETS.heroPizza,
  },

  // ==========================================
  // 7. PREMIUM NON-VEG PIZZA (S / M / L)
  // ==========================================
  {
    id: 'nvp-1',
    name: 'Chicken Salami Pizza',
    description: 'Savory sliced chicken salami over herb tomato sauce and extra Mozzarella.',
    category: 'pizza-nonveg',
    highlightGroup: 'pizza',
    dietary: 'non-veg',
    price: 500,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 500 },
      { label: 'Medium (M)', shortLabel: 'M', price: 900 },
      { label: 'Large (L)', shortLabel: 'L', price: 1300 },
    ],
    tag: 'Non-Veg Premium',
    image: ASSETS.heroPizza,
  },
  {
    id: 'nvp-2',
    name: 'Smoky Crispy Bacon Pizza',
    description: 'Smoky crispy bacon strips with caramelized onion and pulled Mozzarella.',
    category: 'pizza-nonveg',
    highlightGroup: 'pizza',
    dietary: 'non-veg',
    price: 500,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 500 },
      { label: 'Medium (M)', shortLabel: 'M', price: 900 },
      { label: 'Large (L)', shortLabel: 'L', price: 1300 },
    ],
    tag: 'Non-Veg Premium',
    image: ASSETS.heroPizza,
  },
  {
    id: 'nvp-3',
    name: 'Indi Chicken Tikka Pizza',
    description: 'Char-grilled chicken tikka, onion, capsicum, red paprika, and mint mayo drizzle.',
    category: 'pizza-nonveg',
    highlightGroup: 'pizza',
    dietary: 'non-veg',
    price: 500,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 500 },
      { label: 'Medium (M)', shortLabel: 'M', price: 900 },
      { label: 'Large (L)', shortLabel: 'L', price: 1300 },
    ],
    tag: 'Non-Veg Premium',
    popular: true,
    image: ASSETS.heroPizza,
  },
  {
    id: 'nvp-4',
    name: 'Deluxe Chicken Pizza',
    description: 'BBQ chicken, chicken sausage, onion, capsicum, mushroom, and extra cheese.',
    category: 'pizza-nonveg',
    highlightGroup: 'pizza',
    dietary: 'non-veg',
    price: 550,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 550 },
      { label: 'Medium (M)', shortLabel: 'M', price: 1000 },
      { label: 'Large (L)', shortLabel: 'L', price: 1400 },
    ],
    tag: 'Non-Veg Premium',
    image: ASSETS.heroPizza,
  },
  {
    id: 'nvp-5',
    name: 'Meat Lovers Pizza',
    description: 'Loaded with chicken salami, chicken sausage, BBQ chicken, and peri-peri chicken.',
    category: 'pizza-nonveg',
    highlightGroup: 'pizza',
    dietary: 'non-veg',
    price: 550,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 550 },
      { label: 'Medium (M)', shortLabel: 'M', price: 1000 },
      { label: 'Large (L)', shortLabel: 'L', price: 1400 },
    ],
    tag: 'Non-Veg Premium',
    popular: true,
    image: ASSETS.heroPizza,
  },

  // ==========================================
  // 8. SUPREME NON-VEG PIZZA (S / M / L)
  // ==========================================
  {
    id: 'nvs-1',
    name: 'Chicken Over-Loaded Pizza',
    description: 'The ultimate non-veg feast loaded with 4 chicken toppings, black olives, jalapenos, and extra cheese.',
    category: 'pizza-nonveg',
    highlightGroup: 'pizza',
    dietary: 'non-veg',
    price: 600,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 600 },
      { label: 'Medium (M)', shortLabel: 'M', price: 1050 },
      { label: 'Large (L)', shortLabel: 'L', price: 1500 },
    ],
    tag: 'Non-Veg Supreme',
    popular: true,
    image: ASSETS.heroPizza,
  },
  {
    id: 'nvs-2',
    name: 'Hashtag Special Chicken Pizza',
    description: 'Our signature house special loaded with tandoori chicken, salami, sausage, peri-peri chicken, olives & liquid cheese.',
    category: 'pizza-nonveg',
    highlightGroup: 'pizza',
    dietary: 'non-veg',
    price: 600,
    sizes: [
      { label: 'Small (S)', shortLabel: 'S', price: 600 },
      { label: 'Medium (M)', shortLabel: 'M', price: 1050 },
      { label: 'Large (L)', shortLabel: 'L', price: 1500 },
    ],
    tag: 'Chef Signature',
    popular: true,
    image: ASSETS.heroPizza,
  },

  // ==========================================
  // 9. PIZZA LOVERS & MOMO'S PIZZA
  // ==========================================
  {
    id: 'pl-1',
    name: 'Onion Pizza (Pizza Lovers)',
    description: 'Personal single-topping pizza with crunchy onion and real Mozzarella.',
    category: 'pizza-special',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 180,
    tag: 'Pizza Lovers',
    image: ASSETS.categoryPizza,
  },
  {
    id: 'pl-2',
    name: 'Tomato Pizza (Pizza Lovers)',
    description: 'Personal single-topping pizza with fresh juicy tomato and Mozzarella.',
    category: 'pizza-special',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 180,
    tag: 'Pizza Lovers',
    image: ASSETS.categoryPizza,
  },
  {
    id: 'pl-3',
    name: 'Golden Corn Pizza (Pizza Lovers)',
    description: 'Personal pizza topped with sweet golden corn and Mozzarella cheese.',
    category: 'pizza-special',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 180,
    tag: 'Pizza Lovers',
    image: ASSETS.categoryPizza,
  },
  {
    id: 'pl-4',
    name: 'Capsicum Pizza (Pizza Lovers)',
    description: 'Personal pizza with crisp green capsicum and melted Mozzarella.',
    category: 'pizza-special',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 200,
    tag: 'Pizza Lovers',
    image: ASSETS.categoryPizza,
  },
  {
    id: 'pl-5',
    name: 'Paneer Onion Pizza (Pizza Lovers)',
    description: 'Personal pizza topped with spiced paneer cubes and crunchy onion.',
    category: 'pizza-special',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 240,
    tag: 'Pizza Lovers',
    image: ASSETS.categoryPizza,
  },
  {
    id: 'pl-6',
    name: 'Chicken Sausage Pizza (Pizza Lovers)',
    description: 'Personal pizza topped with savory chicken sausage and Mozzarella.',
    category: 'pizza-special',
    highlightGroup: 'pizza',
    dietary: 'non-veg',
    price: 200,
    tag: 'Pizza Lovers',
    image: ASSETS.heroPizza,
  },
  {
    id: 'pl-7',
    name: 'Chicken Pizza (Pizza Lovers)',
    description: 'Personal pizza loaded with spiced chicken chunks and Mozzarella.',
    category: 'pizza-special',
    highlightGroup: 'pizza',
    dietary: 'non-veg',
    price: 240,
    tag: 'Pizza Lovers',
    image: ASSETS.heroPizza,
  },
  {
    id: 'mp-1',
    name: 'Classic Veg Momo Pizza',
    description: 'Unique fusion pizza ringed with juicy veg momos, Mozzarella cheese, and spicy schezwan-herb sauce.',
    category: 'pizza-special',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 280,
    tag: "Momo's Pizza",
    popular: true,
    image: ASSETS.categoryPizza,
  },
  {
    id: 'mp-2',
    name: 'Premium Paneer Momo Pizza',
    description: 'Fusion pizza topped with spiced paneer momos, veggies, and molten Mozzarella.',
    category: 'pizza-special',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 320,
    tag: "Momo's Pizza",
    image: ASSETS.categoryPizza,
  },
  {
    id: 'mp-3',
    name: 'Chicken Momo Pizza',
    description: 'Fusion pizza loaded with juicy chicken momos, stretchy cheese, and zesty pizza sauce.',
    category: 'pizza-special',
    highlightGroup: 'pizza',
    dietary: 'non-veg',
    price: 320,
    tag: "Momo's Pizza",
    popular: true,
    image: ASSETS.heroPizza,
  },

  // ==========================================
  // 10. MOMOS (VEG / PANEER / CHICKEN)
  // ==========================================
  {
    id: 'mm-c1',
    name: 'Chicken Steam / Fried / Pan-Fried Momo',
    description: 'Fresh and juicy chicken momos prepared daily in store, served with spicy house chutney.',
    category: 'momo',
    highlightGroup: 'momo',
    dietary: 'non-veg',
    price: 200,
    sizes: [
      { label: 'Steamed', shortLabel: 'Steam', price: 200 },
      { label: 'Fried', shortLabel: 'Fried', price: 220 },
      { label: 'Pan-Fried', shortLabel: 'Pan-Fried', price: 240 },
    ],
    tag: 'Chicken Momo',
    popular: true,
    image: ASSETS.categoryMomo,
  },
  {
    id: 'mm-c2',
    name: 'Chicken Crispy / Kurkure / Jhol Momo',
    description: 'Choose extra-crunchy Crispy or Kurkure coating, or tangy Himalayan spiced Jhol broth.',
    category: 'momo',
    highlightGroup: 'momo',
    dietary: 'non-veg',
    price: 240,
    sizes: [
      { label: 'Crispy Momo', shortLabel: 'Crispy', price: 240 },
      { label: 'Kurkure Momo', shortLabel: 'Kurkure', price: 260 },
      { label: 'Jhol Momo', shortLabel: 'Jhol', price: 260 },
    ],
    tag: 'Bestseller',
    popular: true,
    image: ASSETS.categoryMomo,
  },
  {
    id: 'mm-c3',
    name: 'Chicken Chilly / Manchurian / Malai Momo',
    description: 'Wok-tossed in spicy Chilly bell-pepper glaze, Indo-Chinese Manchurian gravy, or rich creamy Malai sauce.',
    category: 'momo',
    highlightGroup: 'momo',
    dietary: 'non-veg',
    price: 260,
    sizes: [
      { label: 'Chilly Momo', shortLabel: 'Chilly', price: 260 },
      { label: 'Manchurian', shortLabel: 'Manchurian', price: 280 },
      { label: 'Malai Momo', shortLabel: 'Malai', price: 300 },
    ],
    tag: 'Chicken Momo',
    image: ASSETS.categoryMomo,
  },
  {
    id: 'mm-v1',
    name: 'Veg Steamed / Fried / Pan-Fried Momo',
    description: 'Delicate dumplings stuffed with finely chopped seasoned vegetables and served with spicy tomato achar.',
    category: 'momo',
    highlightGroup: 'momo',
    dietary: 'veg',
    price: 180,
    sizes: [
      { label: 'Steamed', shortLabel: 'Steam', price: 180 },
      { label: 'Fried', shortLabel: 'Fried', price: 200 },
      { label: 'Pan-Fried', shortLabel: 'Pan-Fried', price: 200 },
    ],
    tag: 'Veg Momo',
    image: ASSETS.categoryMomo,
  },
  {
    id: 'mm-v2',
    name: 'Veg Crispy / Kurkure / Jhol Momo',
    description: 'Golden crunchy Crispy or Kurkure veg momos, or steeped in aromatic sesame-tomato Jhol.',
    category: 'momo',
    highlightGroup: 'momo',
    dietary: 'veg',
    price: 220,
    sizes: [
      { label: 'Crispy Momo', shortLabel: 'Crispy', price: 220 },
      { label: 'Kurkure Momo', shortLabel: 'Kurkure', price: 240 },
      { label: 'Jhol Momo', shortLabel: 'Jhol', price: 240 },
    ],
    tag: 'Veg Momo',
    popular: true,
    image: ASSETS.categoryMomo,
  },
  {
    id: 'mm-v3',
    name: 'Veg Chilly / Manchurian / Malai Momo',
    description: 'Veg momos tossed in fiery Chilly sauce, Manchurian gravy, or velvety roasted Malai sauce.',
    category: 'momo',
    highlightGroup: 'momo',
    dietary: 'veg',
    price: 240,
    sizes: [
      { label: 'Chilly Momo', shortLabel: 'Chilly', price: 240 },
      { label: 'Manchurian', shortLabel: 'Manchurian', price: 260 },
      { label: 'Malai Momo', shortLabel: 'Malai', price: 280 },
    ],
    tag: 'Veg Momo',
    image: ASSETS.categoryMomo,
  },
  {
    id: 'mm-p1',
    name: 'Paneer Steamed / Fried / Pan-Fried Momo',
    description: 'Filled with spiced grated malai paneer, onions, and herbs.',
    category: 'momo',
    highlightGroup: 'momo',
    dietary: 'veg',
    price: 220,
    sizes: [
      { label: 'Steamed', shortLabel: 'Steam', price: 220 },
      { label: 'Fried', shortLabel: 'Fried', price: 240 },
      { label: 'Pan-Fried', shortLabel: 'Pan-Fried', price: 240 },
    ],
    tag: 'Paneer Momo',
    image: ASSETS.categoryMomo,
  },
  {
    id: 'mm-p2',
    name: 'Paneer Crispy / Kurkure / Jhol Momo',
    description: 'Crunchy Crispy or Kurkure crusted paneer momos, or served in warm spiced Jhol soup.',
    category: 'momo',
    highlightGroup: 'momo',
    dietary: 'veg',
    price: 260,
    sizes: [
      { label: 'Crispy Momo', shortLabel: 'Crispy', price: 260 },
      { label: 'Kurkure Momo', shortLabel: 'Kurkure', price: 280 },
      { label: 'Jhol Momo', shortLabel: 'Jhol', price: 280 },
    ],
    tag: 'Paneer Momo',
    image: ASSETS.categoryMomo,
  },
  {
    id: 'mm-p3',
    name: 'Paneer Chilly / Manchurian / Malai Momo',
    description: 'Paneer momos finished in hot Chilly pepper toss, Manchurian sauce, or creamy Malai gravy.',
    category: 'momo',
    highlightGroup: 'momo',
    dietary: 'veg',
    price: 280,
    sizes: [
      { label: 'Chilly Momo', shortLabel: 'Chilly', price: 280 },
      { label: 'Manchurian', shortLabel: 'Manchurian', price: 300 },
      { label: 'Malai Momo', shortLabel: 'Malai', price: 320 },
    ],
    tag: 'Paneer Momo',
    image: ASSETS.categoryMomo,
  },

  // ==========================================
  // 11. BURGERS & SANDWICHES
  // ==========================================
  {
    id: 'bg-1',
    name: 'Small Aloo Tikki Burger',
    description: 'Pocket-friendly crispy potato-pea tikki burger with fresh onion and tangy burger mayo.',
    category: 'burger-sandwich',
    highlightGroup: 'burger',
    dietary: 'veg',
    price: 100,
    tag: 'Value Pick',
    image: ASSETS.categoryBurger,
  },
  {
    id: 'bg-2',
    name: 'Crispy Aloo Tikki Burger',
    description: 'Full-sized golden Aloo Tikki patty with crisp veggies and signature dressing. Optional cheese slice.',
    category: 'burger-sandwich',
    highlightGroup: 'burger',
    dietary: 'veg',
    price: 150,
    sizes: [
      { label: 'Regular', shortLabel: 'Regular', price: 150 },
      { label: 'With Cheese', shortLabel: 'Cheese', price: 200 },
    ],
    tag: 'Veg Burger',
    popular: true,
    image: ASSETS.categoryBurger,
  },
  {
    id: 'bg-3',
    name: 'Big Crunchy Veg Burger',
    description: 'Extra-crunchy herb vegetable patty with lettuce, onion rings, and creamy burger sauce.',
    category: 'burger-sandwich',
    highlightGroup: 'burger',
    dietary: 'veg',
    price: 150,
    sizes: [
      { label: 'Big Crunchy', shortLabel: 'Regular', price: 150 },
      { label: 'Big Cheesy', shortLabel: 'Cheese', price: 200 },
    ],
    tag: 'Veg Burger',
    image: ASSETS.categoryBurger,
  },
  {
    id: 'bg-4',
    name: 'Crispy Paneer Burger',
    description: 'Crumb-fried spiced paneer patty layered with veggies and house chipotle mayo.',
    category: 'burger-sandwich',
    highlightGroup: 'burger',
    dietary: 'veg',
    price: 200,
    sizes: [
      { label: 'Regular', shortLabel: 'Regular', price: 200 },
      { label: 'With Cheese', shortLabel: 'Cheese', price: 250 },
    ],
    tag: 'Popular',
    popular: true,
    image: ASSETS.categoryBurger,
  },
  {
    id: 'bg-5',
    name: 'Burger Pizza',
    description: 'Baked burger bun stuffed with pizza sauce, sweet corn, capsicum, onion, and pulled Mozzarella.',
    category: 'burger-sandwich',
    highlightGroup: 'burger',
    dietary: 'veg',
    price: 200,
    tag: 'Fusion',
    image: ASSETS.categoryBurger,
  },
  {
    id: 'bg-6',
    name: 'Maharaja Burger',
    description: 'Towering double-decker burger with dual crispy patties, rich cheese, jalapenos, and signature sauce.',
    category: 'burger-sandwich',
    highlightGroup: 'burger',
    dietary: 'veg',
    price: 350,
    tag: 'King Size',
    popular: true,
    image: ASSETS.categoryBurger,
  },
  {
    id: 'bg-7',
    name: 'Chicken Patty Burger',
    description: 'Fried chicken patty prepared fresh in-store, loaded with creamy mayo sauce and crisp veggies.',
    category: 'burger-sandwich',
    highlightGroup: 'burger',
    dietary: 'non-veg',
    price: 180,
    sizes: [
      { label: 'Regular', shortLabel: 'Regular', price: 180 },
      { label: 'With Cheese', shortLabel: 'Cheese', price: 230 },
    ],
    tag: 'Chicken Burger',
    popular: true,
    image: ASSETS.categoryBurger,
  },
  {
    id: 'bg-8',
    name: 'Chicken Zinger Burger',
    description: 'Signature crunchy CFC-style fried chicken fillet in a toasted sesame bun with lettuce and mayo.',
    category: 'burger-sandwich',
    highlightGroup: 'burger',
    dietary: 'non-veg',
    price: 200,
    sizes: [
      { label: 'Zinger', shortLabel: 'Regular', price: 200 },
      { label: 'Zinger Cheese', shortLabel: 'Cheese', price: 250 },
    ],
    tag: 'Bestseller',
    popular: true,
    image: ASSETS.categoryBurger,
  },
  {
    id: 'sw-1',
    name: 'Classic Veg Grilled Sandwich',
    description: 'Toasted jumbo bread stuffed with fresh garden vegetables, green chutney, and seasoning.',
    category: 'burger-sandwich',
    highlightGroup: 'burger',
    dietary: 'veg',
    price: 150,
    sizes: [
      { label: 'Classic', shortLabel: 'Regular', price: 150 },
      { label: 'With Cheese', shortLabel: 'Cheese', price: 200 },
    ],
    tag: 'Sandwich',
    image: ASSETS.categoryBurger,
  },
  {
    id: 'sw-2',
    name: 'Premium Paneer Grilled Sandwich',
    description: 'Grilled sandwich loaded with spiced paneer cubes, capsicum, onion, and optional melted cheese.',
    category: 'burger-sandwich',
    highlightGroup: 'burger',
    dietary: 'veg',
    price: 200,
    sizes: [
      { label: 'Regular', shortLabel: 'Regular', price: 200 },
      { label: 'With Cheese', shortLabel: 'Cheese', price: 250 },
    ],
    tag: 'Sandwich',
    image: ASSETS.categoryBurger,
  },
  {
    id: 'sw-3',
    name: 'Chicken Grilled Sandwich',
    description: 'Loaded with tender seasoned chicken chunks, onion, capsicum, and creamy dressing.',
    category: 'burger-sandwich',
    highlightGroup: 'burger',
    dietary: 'non-veg',
    price: 200,
    sizes: [
      { label: 'Regular', shortLabel: 'Regular', price: 200 },
      { label: 'With Cheese', shortLabel: 'Cheese', price: 250 },
    ],
    tag: 'Sandwich',
    image: ASSETS.categoryBurger,
  },

  // ==========================================
  // 12. CFC STRIPS & NON-VEG SIDES
  // ==========================================
  {
    id: 'cfc-1',
    name: 'CFC Boneless Crispy Chicken Strips (4 / 6 Pcs)',
    description: 'Tender boneless chicken breast strips breaded in our crunchy spice blend and fried golden.',
    category: 'cfc-nonveg-sides',
    highlightGroup: 'cfc',
    dietary: 'non-veg',
    price: 250,
    sizes: [
      { label: '4 Pcs Strips', shortLabel: '4 Pcs', price: 250 },
      { label: '6 Pcs Strips', shortLabel: '6 Pcs', price: 350 },
    ],
    tag: 'Signature CFC',
    popular: true,
    image: ASSETS.categoryCfc,
  },
  {
    id: 'cfc-2',
    name: 'CFC Boneless Chicken Strips Bucket (8 / 12 Pcs)',
    description: 'Shareable bucket of extra-crunchy boneless chicken strips served hot with signature dips.',
    category: 'cfc-nonveg-sides',
    highlightGroup: 'cfc',
    dietary: 'non-veg',
    price: 450,
    sizes: [
      { label: '8 Pcs Strips', shortLabel: '8 Pcs', price: 450 },
      { label: '12 Pcs Strips', shortLabel: '12 Pcs', price: 650 },
    ],
    tag: 'Party Bucket',
    popular: true,
    image: ASSETS.categoryCfc,
  },
  {
    id: 'cfc-3',
    name: 'Crispy Chicken Popcorn',
    description: 'Bite-sized crunchy fried chicken popcorn dusted with tangy peri-peri seasoning.',
    category: 'cfc-nonveg-sides',
    highlightGroup: 'cfc',
    dietary: 'non-veg',
    price: 250,
    tag: 'Bestseller',
    popular: true,
    image: ASSETS.categoryCfc,
  },
  {
    id: 'cfc-4',
    name: 'Crispy Chicken Nuggets',
    description: 'Golden crumb-coated tender chicken nuggets served with mayo and ketchup.',
    category: 'cfc-nonveg-sides',
    highlightGroup: 'cfc',
    dietary: 'non-veg',
    price: 250,
    tag: 'Crispy',
    image: ASSETS.categoryCfc,
  },
  {
    id: 'cfc-5',
    name: 'Fried Chicken Sausage',
    description: 'Juicy smoked chicken sausages flash-fried and served with spicy dip.',
    category: 'cfc-nonveg-sides',
    highlightGroup: 'cfc',
    dietary: 'non-veg',
    price: 180,
    sizes: [
      { label: '2 Pieces', shortLabel: '2 Pcs', price: 180 },
      { label: '5 Pieces', shortLabel: '5 Pcs', price: 400 },
    ],
    image: ASSETS.categoryCfc,
  },
  {
    id: 'cfc-6',
    name: 'Stuffed Chicken Garlic Bread',
    description: 'Freshly baked garlic bread stuffed with spiced chicken chunks, sweet corn, and molten Mozzarella.',
    category: 'cfc-nonveg-sides',
    highlightGroup: 'cfc',
    dietary: 'non-veg',
    price: 300,
    tag: 'Must Try',
    popular: true,
    image: ASSETS.categoryPizza,
  },
  {
    id: 'cfc-7',
    name: 'Chicken Parcel',
    description: 'Folded golden pastry triangle baked with harissa-spiced chicken and melted cheese.',
    category: 'cfc-nonveg-sides',
    highlightGroup: 'cfc',
    dietary: 'non-veg',
    price: 100,
    image: ASSETS.categoryPizza,
  },
  {
    id: 'cfc-8',
    name: 'Chicken Chilly / Chicken Manchurian / Chilly Sausage',
    description: 'Crispy fried chicken or sausage wok-tossed with bell peppers, onions, and fiery Indo-Chinese sauces.',
    category: 'cfc-nonveg-sides',
    highlightGroup: 'cfc',
    dietary: 'non-veg',
    price: 320,
    sizes: [
      { label: 'Chicken Chilly', shortLabel: 'Chilly', price: 320 },
      { label: 'Manchurian', shortLabel: 'Manchurian', price: 320 },
      { label: 'Chilly Sausage', shortLabel: 'Sausage', price: 320 },
    ],
    tag: 'Spicy Starter',
    image: ASSETS.categoryCfc,
  },

  // ==========================================
  // 13. GARLIC BREAD, FRIES, PASTA & APPETIZERS
  // ==========================================
  {
    id: 'sp-1',
    name: 'Garlic Bread (Plain / Classic Stuffed / Paneer Stuffed)',
    description: 'Freshly baked in-store garlic bread brushed with herb butter. Choose plain or stuffed with Mozzarella.',
    category: 'sides-pasta',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 200,
    sizes: [
      { label: 'Plain Garlic Bread', shortLabel: 'Plain', price: 200 },
      { label: 'Classic Stuffed', shortLabel: 'Stuffed', price: 280 },
      { label: 'Paneer Stuffed', shortLabel: 'Paneer', price: 350 },
    ],
    tag: 'Bestseller',
    popular: true,
    image: ASSETS.categoryPizza,
  },
  {
    id: 'sp-2',
    name: 'Veg Parcel',
    description: 'Baked herb dough parcel filled with spiced paneer, golden corn, and melted cheese.',
    category: 'sides-pasta',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 100,
    image: ASSETS.categoryPizza,
  },
  {
    id: 'sp-3',
    name: 'French Fries (Classic / Peri Peri / Cheezy)',
    description: 'Crispy golden french fries served salted, dusted with zesty Peri-Peri, or loaded with melted cheese.',
    category: 'sides-pasta',
    highlightGroup: 'burger',
    dietary: 'veg',
    price: 180,
    sizes: [
      { label: 'Classic Fries', shortLabel: 'Classic', price: 180 },
      { label: 'Peri Peri Fries', shortLabel: 'Peri Peri', price: 200 },
      { label: 'Cheezy Fries', shortLabel: 'Cheezy', price: 300 },
    ],
    tag: 'Fries',
    popular: true,
    image: ASSETS.categoryBurger,
  },
  {
    id: 'sp-4',
    name: 'Potato Cheese Shots with Mayo Dip',
    description: 'Crispy golden potato-cheese bites served hot with creamy garlic mayo dip.',
    category: 'sides-pasta',
    highlightGroup: 'burger',
    dietary: 'veg',
    price: 250,
    image: ASSETS.categoryBurger,
  },
  {
    id: 'sp-5',
    name: 'Paneer Popcorn / Crispy Paneer Sticks / Chilly Potatoes',
    description: 'Crunchy crumb-fried paneer bites or honey-chilly glazed crispy potato fingers.',
    category: 'sides-pasta',
    highlightGroup: 'all',
    dietary: 'veg',
    price: 300,
    sizes: [
      { label: 'Paneer Popcorn', shortLabel: 'Popcorn', price: 300 },
      { label: 'Paneer Sticks', shortLabel: 'Sticks', price: 300 },
      { label: 'Chilly Potatoes', shortLabel: 'Chilly Pot.', price: 300 },
    ],
    tag: 'Appetizer',
    image: ASSETS.categoryCfc,
  },
  {
    id: 'sp-6',
    name: 'Chilly Paneer / Chilly Mushroom',
    description: 'Cubes of cottage cheese or fresh button mushrooms wok-tossed in spicy soy-chilly pepper sauce.',
    category: 'sides-pasta',
    highlightGroup: 'all',
    dietary: 'veg',
    price: 320,
    sizes: [
      { label: 'Chilly Paneer', shortLabel: 'Paneer', price: 320 },
      { label: 'Chilly Mushroom', shortLabel: 'Mushroom', price: 320 },
    ],
    tag: 'Appetizer',
    image: ASSETS.categoryMomo,
  },
  {
    id: 'sp-7',
    name: 'Veg Manchurian (Dry / Gravy) / Veg Wonton',
    description: 'Crispy vegetable dumplings in garlic-cilantro Manchurian sauce, or golden fried veg wontons.',
    category: 'sides-pasta',
    highlightGroup: 'all',
    dietary: 'veg',
    price: 250,
    sizes: [
      { label: 'Veg Wonton', shortLabel: 'Wonton', price: 250 },
      { label: 'Manchurian Dry', shortLabel: 'Dry', price: 260 },
      { label: 'Manchurian Gravy', shortLabel: 'Gravy', price: 260 },
    ],
    image: ASSETS.categoryMomo,
  },
  {
    id: 'sp-8',
    name: 'Veg Pasta (White Sauce / Red Sauce / Mix / Cheezy)',
    description: 'Penne pasta tossed with sweet corn, bell peppers, olives, and herbs in rich Italian sauces.',
    category: 'sides-pasta',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 300,
    sizes: [
      { label: 'White / Red', shortLabel: 'Regular', price: 300 },
      { label: 'Mix Sauce', shortLabel: 'Mix', price: 320 },
      { label: 'Baked Cheezy', shortLabel: 'Cheezy', price: 350 },
    ],
    tag: 'Veg Pasta',
    image: ASSETS.categoryPizza,
  },
  {
    id: 'sp-9',
    name: 'Chicken Pasta (White Sauce / Red Sauce / Mix Sauce)',
    description: 'Penne pasta with tender spiced chicken chunks, herbs, and parmesan-mozzarella sauce.',
    category: 'sides-pasta',
    highlightGroup: 'pizza',
    dietary: 'non-veg',
    price: 320,
    sizes: [
      { label: 'White Sauce', shortLabel: 'White', price: 320 },
      { label: 'Red Sauce', shortLabel: 'Red', price: 320 },
      { label: 'Mix Sauce', shortLabel: 'Mix', price: 340 },
    ],
    tag: 'Chicken Pasta',
    image: ASSETS.categoryPizza,
  },

  // ==========================================
  // 14. NOODLES, FRIED RICE, ROLLS & BOWL COMBOS
  // ==========================================
  {
    id: 'nr-1',
    name: 'Veg Noodles (Veg / Hakka / Schezwan / Paneer)',
    description: 'High-flame wok-tossed noodles with crisp julienned vegetables and house seasoning.',
    category: 'noodles-rice-rolls',
    highlightGroup: 'all',
    dietary: 'veg',
    price: 200,
    sizes: [
      { label: 'Veg / Hakka', shortLabel: 'Veg/Hakka', price: 200 },
      { label: 'Schezwan', shortLabel: 'Schezwan', price: 220 },
      { label: 'Paneer Noodles', shortLabel: 'Paneer', price: 260 },
    ],
    tag: 'Noodles',
    image: ASSETS.categoryMomo,
  },
  {
    id: 'nr-2',
    name: 'Chicken Chowmein / Popcorn / Schezwan Noodles',
    description: 'Street-style wok-tossed noodles loaded with tender chicken strips or crunchy chicken popcorn.',
    category: 'noodles-rice-rolls',
    highlightGroup: 'all',
    dietary: 'non-veg',
    price: 260,
    sizes: [
      { label: 'Chicken Chowmein', shortLabel: 'Chicken', price: 260 },
      { label: 'Popcorn Noodles', shortLabel: 'Popcorn', price: 260 },
      { label: 'Schezwan Chicken', shortLabel: 'Schezwan', price: 280 },
    ],
    tag: 'Bestseller',
    popular: true,
    image: ASSETS.categoryMomo,
  },
  {
    id: 'nr-3',
    name: 'Veg Fried Rice (Classic / Schezwan / Paneer / Spl. Mix)',
    description: 'Fragrant basmati rice stir-fried with garden vegetables, spring onions, and aromatic spices.',
    category: 'noodles-rice-rolls',
    highlightGroup: 'all',
    dietary: 'veg',
    price: 200,
    sizes: [
      { label: 'Veg Fried Rice', shortLabel: 'Veg', price: 200 },
      { label: 'Schezwan Rice', shortLabel: 'Schezwan', price: 220 },
      { label: 'Paneer Rice', shortLabel: 'Paneer', price: 240 },
      { label: 'Spl. Mix Rice', shortLabel: 'Spl. Mix', price: 280 },
    ],
    tag: 'Fried Rice',
    image: ASSETS.categoryMomo,
  },
  {
    id: 'nr-4',
    name: 'Chicken Fried Rice (Classic / Popcorn / Schezwan)',
    description: 'Wok-tossed basmati rice with roasted chicken, egg, spring onions, and savory soy-garlic notes.',
    category: 'noodles-rice-rolls',
    highlightGroup: 'all',
    dietary: 'non-veg',
    price: 260,
    sizes: [
      { label: 'Chicken Rice', shortLabel: 'Chicken', price: 260 },
      { label: 'Popcorn Rice', shortLabel: 'Popcorn', price: 260 },
      { label: 'Schezwan Chicken', shortLabel: 'Schezwan', price: 280 },
    ],
    tag: 'Fried Rice',
    image: ASSETS.categoryMomo,
  },
  {
    id: 'nr-5',
    name: 'Veg Rolls & Wraps (Veg / Chowmein / Paneer / Mushroom)',
    description: 'Flaky toasted paratha wrap stuffed with crunchy onions, sauces, and your choice of filling.',
    category: 'noodles-rice-rolls',
    highlightGroup: 'all',
    dietary: 'veg',
    price: 120,
    sizes: [
      { label: 'Veg Roll', shortLabel: 'Veg', price: 120 },
      { label: 'Veg Chowmein', shortLabel: 'Chowmein', price: 150 },
      { label: 'Paneer / Mushroom', shortLabel: 'Paneer', price: 200 },
    ],
    tag: 'Rolls',
    image: ASSETS.categoryBurger,
  },
  {
    id: 'nr-6',
    name: 'Chicken Kathi / Popcorn / Chowmein / Special Roll',
    description: 'Loaded paratha wrap filled with smoky chicken kathi kebab, crunchy chicken popcorn, or chowmein.',
    category: 'noodles-rice-rolls',
    highlightGroup: 'all',
    dietary: 'non-veg',
    price: 250,
    sizes: [
      { label: 'Chicken Kathi', shortLabel: 'Kathi', price: 250 },
      { label: 'Chicken Popcorn', shortLabel: 'Popcorn', price: 250 },
      { label: 'Special Roll', shortLabel: 'Special', price: 250 },
    ],
    tag: 'Rolls',
    popular: true,
    image: ASSETS.categoryBurger,
  },
  {
    id: 'nr-7',
    name: 'Veg Bowl Combo (Manchurian or Chilly Paneer)',
    description: 'Complete meal bowl pairing Fried Rice or Noodles with hot Veg Manchurian or Chilly Paneer.',
    category: 'noodles-rice-rolls',
    highlightGroup: 'all',
    dietary: 'veg',
    price: 300,
    sizes: [
      { label: 'Manchurian Bowl', shortLabel: 'Manchurian', price: 300 },
      { label: 'Chilly Paneer Bowl', shortLabel: 'Chilly Paneer', price: 300 },
    ],
    tag: 'Bowl Combo',
    image: ASSETS.categoryMomo,
  },
  {
    id: 'nr-8',
    name: 'Chicken Bowl Combo (Chilly Chicken / Popcorn / Sausage)',
    description: 'Hearty meal bowl of Fried Rice or Noodles topped with Chilly Chicken, Chicken Popcorn, or Chilly Sausage.',
    category: 'noodles-rice-rolls',
    highlightGroup: 'all',
    dietary: 'non-veg',
    price: 350,
    sizes: [
      { label: 'Chilly Chicken Bowl', shortLabel: 'Chilly Chkn', price: 350 },
      { label: 'Popcorn Bowl', shortLabel: 'Popcorn', price: 350 },
      { label: 'Chilly Sausage Bowl', shortLabel: 'Sausage', price: 350 },
    ],
    tag: 'Bowl Combo',
    image: ASSETS.categoryMomo,
  },

  // ==========================================
  // 15. MOCKTAILS, SHAKES & DESSERTS
  // ==========================================
  {
    id: 'dd-1',
    name: 'Choco Lava Cake & Waffles',
    description: 'Warm molten Choco Lava Cake or freshly baked crispy Belgian waffles with chocolate drizzle.',
    category: 'drinks-desserts',
    highlightGroup: 'all',
    dietary: 'veg',
    price: 120,
    sizes: [
      { label: 'Choco Lava Cake', shortLabel: 'Choco Lava', price: 120 },
      { label: 'Choc / White Waffle', shortLabel: 'Waffle', price: 200 },
      { label: 'KitKat Waffle', shortLabel: 'KitKat', price: 250 },
    ],
    tag: 'Desserts',
    popular: true,
    image: ASSETS.categoryBurger,
  },
  {
    id: 'dd-2',
    name: 'Refreshing Mocktails & Coolers',
    description: 'Chilled Mint Mojito, Blue Lagoon, Mix Fruit Mania, Ice Tea, Kala Khatta, or Cold Coffee.',
    category: 'drinks-desserts',
    highlightGroup: 'all',
    dietary: 'veg',
    price: 150,
    sizes: [
      { label: 'Masala / Lime Soda', shortLabel: 'Soda', price: 150 },
      { label: 'Mojito / Blue Lagoon', shortLabel: 'Mocktail', price: 180 },
      { label: 'Cold Coffee / Ice Tea', shortLabel: 'Coffee', price: 180 },
    ],
    tag: 'Mocktails',
    popular: true,
    image: ASSETS.categoryBurger,
  },
  {
    id: 'dd-3',
    name: 'Classic, Fruit & Chocolate Thick Shakes',
    description: 'Creamy dairy shakes in Vanilla, Butterscotch, Mango, Strawberry, Berry Blast, Oreo, or KitKat.',
    category: 'drinks-desserts',
    highlightGroup: 'all',
    dietary: 'veg',
    price: 180,
    sizes: [
      { label: 'Classic / Fruit Shake', shortLabel: 'Classic', price: 180 },
      { label: 'Kesar Badam Shake', shortLabel: 'Kesar', price: 200 },
      { label: 'Oreo / KitKat Shake', shortLabel: 'Oreo/KitKat', price: 220 },
    ],
    tag: 'Thick Shakes',
    image: ASSETS.categoryBurger,
  },
  {
    id: 'dd-4',
    name: 'Iced Cold Drink & Signature Dips',
    description: 'Chilled glass of Iced Cold Drink (Rs. 100) or extra house dips: Mayo, Cheesy, Jalapeno, or Harissa (Rs. 40).',
    category: 'drinks-desserts',
    highlightGroup: 'all',
    dietary: 'veg',
    price: 40,
    sizes: [
      { label: 'Signature Dip', shortLabel: 'Dip', price: 40 },
      { label: 'Iced Cold Drink', shortLabel: 'Cold Drink', price: 100 },
    ],
    image: ASSETS.categoryBurger,
  },

  // ==========================================
  // 16. OFFICIAL COMBO OFFERS
  // ==========================================
  {
    id: 'cb-1',
    name: 'Veg Couple Combo',
    description: 'Includes 1 Farmhouse Small Pizza + 1 Veg Burger + 250ml Cold Drink.',
    category: 'combos',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 500,
    tag: 'Bestseller Combo',
    popular: true,
    image: ASSETS.categoryPizza,
  },
  {
    id: 'cb-2',
    name: 'Non-Veg Couple Combo',
    description: 'Curated couple meal with Small Non-Veg Pizza, Chicken Burger/Side, and Cold Drink.',
    category: 'combos',
    highlightGroup: 'pizza',
    dietary: 'non-veg',
    price: 750,
    tag: 'Couple Deal',
    popular: true,
    image: ASSETS.heroPizza,
  },
  {
    id: 'cb-3',
    name: 'Veg Triple Combo & Non-Veg Triple Combo',
    description: 'Group party combos loaded with pizzas, sides, and drinks for 3–4 people.',
    category: 'combos',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 950,
    sizes: [
      { label: 'Veg Triple Combo', shortLabel: 'Veg Triple', price: 950 },
      { label: 'Non-Veg Triple Combo', shortLabel: 'Non-Veg Triple', price: 1150 },
    ],
    tag: 'Triple Pack',
    image: ASSETS.heroPizza,
  },
  {
    id: 'cb-4',
    name: 'Veg Value Combos (Combo 1 & Combo 2)',
    description: 'Pocket-friendly everyday vegetarian meal combos freshly prepared in-store.',
    category: 'combos',
    highlightGroup: 'pizza',
    dietary: 'veg',
    price: 400,
    sizes: [
      { label: 'Veg Combo 1', shortLabel: 'Combo 1', price: 400 },
      { label: 'Veg Combo 2', shortLabel: 'Combo 2', price: 600 },
    ],
    tag: 'Everyday Deal',
    image: ASSETS.categoryPizza,
  },
  {
    id: 'cb-5',
    name: '3 Plate Steam Momo Combo (Veg / Chicken)',
    description: '3 full plates (24 pieces) of piping hot steamed momos with spicy house chutney.',
    category: 'combos',
    highlightGroup: 'momo',
    dietary: 'non-veg',
    price: 500,
    sizes: [
      { label: '3 Plt Veg Momo', shortLabel: 'Veg (3 Plt)', price: 500 },
      { label: '3 Plt Chicken Momo', shortLabel: 'Chicken (3 Plt)', price: 550 },
    ],
    tag: 'Everyday Deal',
    popular: true,
    image: ASSETS.categoryMomo,
  },
  {
    id: 'cb-6',
    name: '4 Aloo Tikki Burger Combo',
    description: '4 freshly toasted Aloo Tikki Burgers with crispy patties and house burger mayo.',
    category: 'combos',
    highlightGroup: 'burger',
    dietary: 'veg',
    price: 500,
    tag: 'Squad Deal',
    popular: true,
    image: ASSETS.categoryBurger,
  },
  {
    id: 'cb-7',
    name: '5 Choco Lava Cake Combo',
    description: '5 warm dark chocolate molten lava cakes—perfect for celebrations and groups.',
    category: 'combos',
    highlightGroup: 'all',
    dietary: 'veg',
    price: 500,
    tag: 'Sweet Pack',
    image: ASSETS.categoryBurger,
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Aayush Shrestha',
    role: 'Resident · Adarshnagar, Birgunj',
    date: 'Google Review',
    rating: '5.0 / 5.0',
    text: 'Before Hashtag Pizza opened in 2022, we had to travel out of town for authentic hand-tossed crust. Their Chicken Over-Loaded Supreme and Wednesday BOGO deal are now our family ritual.',
  },
  {
    id: 2,
    name: 'Priyanka Gupta',
    role: 'College Student · Birgunj Public College',
    date: 'Facebook Review',
    rating: '5.0 / 5.0',
    text: 'The Boneless Chicken Strips and Chicken Kurkure Momos beat international chains hands down. Watching the dough stretched live in the open kitchen at RB Complex gives total confidence in hygiene.',
  },
  {
    id: 3,
    name: 'Rahul Verma',
    role: 'Business Owner · Loharpatti',
    date: 'Google Review',
    rating: '4.9 / 5.0',
    text: 'Ordered the Non-Veg Triple Combo and Chicken Zinger Cheese Burgers for an office team lunch. Delivered piping hot in 30 minutes with real mozzarella that stays stretchy.',
  },
];

// Pizza Size Add-Ons (Rates per size S / M / L)
export interface PizzaAddonOption {
  id: string;
  name: string;
  category: 'pizza-addon';
  description: string;
  prices: {
    S: number;
    M: number;
    L: number;
  };
}

export const PIZZA_SIZE_ADDONS: PizzaAddonOption[] = [
  {
    id: 'addon-cheese-burst',
    name: 'Cheese Burst',
    category: 'pizza-addon',
    description: 'Crust packed with molten melted cheese',
    prices: { S: 120, M: 200, L: 300 },
  },
  {
    id: 'addon-extra-cheese',
    name: 'Extra Cheese',
    category: 'pizza-addon',
    description: 'Extra layer of 100% real mozzarella & cheddar',
    prices: { S: 80, M: 140, L: 200 },
  },
  {
    id: 'addon-veg-topping',
    name: 'Veg Topping',
    category: 'pizza-addon',
    description: 'Fresh crisp capsicum, sweet corn, mushrooms & onions',
    prices: { S: 40, M: 60, L: 80 },
  },
  {
    id: 'addon-chicken-topping',
    name: 'Chicken Topping',
    category: 'pizza-addon',
    description: 'Juicy spiced herb-roasted chicken chunks',
    prices: { S: 60, M: 80, L: 100 },
  },
];

// Dips (Rs. 40 each)
export interface DipAddonOption {
  id: string;
  name: string;
  price: number;
  description: string;
}

export const DIPS_ADDONS: DipAddonOption[] = [
  {
    id: 'dip-cheesy',
    name: 'Cheesy Dip',
    price: 40,
    description: 'Creamy melted cheese dipping sauce',
  },
  {
    id: 'dip-mayo',
    name: 'Mayo Dip',
    price: 40,
    description: 'Rich velvety garlic mayo dip',
  },
  {
    id: 'dip-harisha',
    name: 'Harisha Dip',
    price: 40,
    description: 'Zesty spiced Moroccan chilli harissa dip',
  },
  {
    id: 'dip-mint-mayo',
    name: 'Mint Mayo Dip',
    price: 40,
    description: 'Refreshing fresh mint & herb mayo dip',
  },
];

// Beverages (Bottles only - No Can)
export interface BeverageAddonOption {
  id: string;
  name: string;
  price: number;
  volume: string;
  description: string;
}

export const BEVERAGE_ADDONS: BeverageAddonOption[] = [
  {
    id: 'bev-coke-250',
    name: 'Coke (250 ml Bottle)',
    price: 60,
    volume: '250 ml',
    description: 'Chilled bottle · No can only bottle',
  },
  {
    id: 'bev-sprite-250',
    name: 'Sprite (250 ml Bottle)',
    price: 60,
    volume: '250 ml',
    description: 'Chilled lemon-lime bottle · No can only bottle',
  },
  {
    id: 'bev-fanta-250',
    name: 'Fanta (250 ml Bottle)',
    price: 60,
    volume: '250 ml',
    description: 'Chilled sparkling orange bottle · No can only bottle',
  },
  {
    id: 'bev-coke-750',
    name: 'Coke (750 ml Bottle)',
    price: 120,
    volume: '750 ml',
    description: 'Large sharing chilled bottle',
  },
  {
    id: 'bev-sprite-750',
    name: 'Sprite (750 ml Bottle)',
    price: 120,
    volume: '750 ml',
    description: 'Large sharing chilled bottle',
  },
];
